### PR TITLE
Add support for Uberspace 7

### PR DESCRIPTION
**Pull request by ghost**
Hi Andreas
I just changed changed `uberspace-add-domain -m` to `uberspace mail domain list` and it works fine on uberspace 7 now. Thanks for the plugin!
Maybe you could merge this into a new uberspace 7 branch so other people may use it, too.
Regards,
Leo

### CODE REVIEW

**Comment by realAndrewEagle** [comment]
Hi Leo,

Thanks for your PR. However I would prever an all-in-one solution. Maybe the plugin could check for the uberspace version to decide how to retrieve the domain list.
Maybe one could try to call the uberspace command, which is only present on Uberspace 7 to detect the version?
If you don't want to make this extra work maybe I'll find some time the next days to make the plugin compatible with both uberspace infrastructures.

Regards,
Andreas

**Comment by ghost** [comment]
I am quite busy at the moment and wasn't able to test it for now, seems to work on my local machine. Anyway I don't have access to an uberspace6.
Regards

**Comment by ghost** [comment]
btw the CommandExists function returns the shell exit code: 0 = success | 1 = error

**Comment by realAndrewEagle** [comment]
Hi Leo,

sorry for the late response. I tested your version on my Rainloop installation on my Uberspace 6 account. Unfortunately it didn't work. In fact, the password change menu item disappeared with this version so I guess there is an error thrown in the `PasswordChangePossibility` method (which eventually also calls your changed and added methods).
Maybe you find some time to test it on both, an Uberspace 6 and 7 account. (I assume you already know that you can create free trial Uberspace accounts.)

Thanks again for your efforts. :)

**Pull request closed without merging**
